stages:
- test

test:windows:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: test
  only:
  - develop
  tags:
  - windows
  script:
  - rspec

test:mac:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: test
  only:
  - develop  
  tags:
  - mac
  script:
  - rspec

test:ubuntu:
  variables:
    CI_DEBUG_TRACE: "true"
  stage: test
  only:
  - develop  
  tags:
  - ubuntu
  script:
  - rspec
