AllCops:
  Exclude:
    - 'measures/**/*'
    - 'spec/files/**/measures/**/*'
    - '**/measure.rb'
    - 'spec/files/mongoid/models/**/*'
    - 'spec/files/pat_project/data_point_*/**/*'
    - 'spec/files/pat_project/run/**/*'
    - 'spec/files/mongo_pat1/run/**/*'
require: rubocop-performance
inherit_from:
  - http://s3.amazonaws.com/openstudio-resources/styles/rubocop_v4.yml
