AllCops:
  Exclude:
    - 'measures/**/*'
    - 'spec/files/**/measures/**/*'
    - '**/measure.rb'
    - 'spec/files/mongoid/models/**/*'
    - 'spec/files/pat_project/data_point_*/**/*'
    - 'spec/files/pat_project/run/**/*'
    - 'spec/files/mongo_pat1/run/**/*'

# ==================== Linters ====================
Lint/AmbiguousOperator:
  Enabled: true

Lint/BlockAlignment:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

# Offense count: 1
Lint/UnreachableCode:
  Enabled: false

# Offense count: 51
Lint/UselessAssignment:
  Enabled: true

# ==================== Styles / Metrics====================
# Offense count: 4
Metrics/BlockNesting:
  Max: 4

# Offense count: 18
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 500

# Offense count: 27
Metrics/CyclomaticComplexity:
  Max: 48

# Offense count: 974
Metrics/LineLength:
  Max: 1200

# Offense count: 87
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 350

# Offense count: 1
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 8

# ==================== Disabled on Purpose ====================
# Offense count: 3
Style/AccessorMethodName:
  Enabled: true

# Need to allow indented case statements
# Offense count: 9
# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
Style/CaseIndentation:
  Enabled: false

# Offense count: 18
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 2
Style/ClassVars:
  Enabled: false

# Offense count: 42
Style/Documentation:
  Enabled: false

# Offense count: 1
Style/EachWithObject:
  Enabled: false

# Offense count: 2
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Enabled: false

# Offense count: 7
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: true

# Offense count: 17
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

# Do NOT enable.  For some reason this is catchy any next which I feel are okay.
# Offense count: 18
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/Next:
  Enabled: false

# Do NOT enable this because it appears $? is different than $CHILD_STATUS.
# Offense count: 7
# Cop supports --auto-correct.
Style/SpecialGlobalVars:
  Enabled: false

# More Changes per DLM -- pulled from https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml
Style/RedundantReturn:
  Description: 'Do not use return where it is not required.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-explicit-return'
  Enabled: false

Style/NumericLiterals:
  Description: 'Add underscores to large numeric literals to improve readability.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#underscores-in-numerics'
  Enabled: false

Lint/UnusedBlockArgument:
  Description: 'Checks for unused block arguments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#underscore-unused-vars'
  Enabled: false

Lint/UnusedMethodArgument:
  Description: 'Checks for unused method arguments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#underscore-unused-vars'
  Enabled: false

Lint/UselessAssignment:
  Description: 'Checks for useless assignment to a local variable.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#underscore-unused-vars'
  Enabled: false
