source 'https://supermarket.getchef.com'

cookbook 'apt'
cookbook 'yum'
cookbook 'yum-epel'
cookbook 'gdebi'
cookbook 'build-essential'
cookbook 'ruby_build'
cookbook 'zip'
cookbook 'mongodb'
cookbook 'rbenv'

cookbook 'openstudio', github: 'NREL-cookbooks/openstudio', protocol: 'ssh'
cookbook 'energyplus', github: 'NREL-cookbooks/energyplus', protocol: 'ssh'
# cookbook "energyplus", path: '../energyplus'
cookbook 'ark', github: 'NREL-cookbooks/ark', protocol: 'ssh'
# cookbook "ark", path: '../ark'
